# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker compose configuration file
services:
  hub:
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: latest
    restart: unless-stopped
    image: jupyterhub
    container_name: jupyterhub
    ports:
     - 8000:8000
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: nucleus-jupyter:latest
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan
      DATA_DIRECTORY: jupyterhub-shared-data
      UV_INDEX: https://pypi.org/simple
      NB_USER: jovyan
      NB_UMASK: 022

volumes:
  jupyterhub-data:
  jupyterhub-shared-data:

networks:
  jupyterhub-network:
      name: jupyterhub-network
